### ISSUE TITLE
[Missing contact] Probably my bad but how is possible to contact you?

### ISSUE THREAD

**Issue by drakonkat** [0xQueen/homepage#1]
I found your profile from the project https://new.beta-manager.com/. I see you are a web designer, so I was interested in collaboration on some open source projects to be started if you like the idea
Anyway, trying to contact you, I noticed that there is no link to your discord or anything on your site, so I thought I would point it out to you here.  I hope it is appreciated and not offensive

**Comment by 0xQueen** [comment]
Contact me on my Tox: 038B40F154287CFC762A2B2A5444C1720C9B08F1DEFF13CC9D3B18B4AC74CD52CC25B06BF226
